### ISSUE TITLE
Submit to Open VSX

### ISSUE THREAD

**Issue by ashooner** [wunderio/drupal-sdc-helper#3]
This looks great! We use Gitpod, which means our VS Code extensions need to come from the [Open VSX Registry](https://open-vsx.org/). Any chance of publishing there as well?

**Comment by DavisAre** [comment]
Hi, thanks, will look into this.

**Comment by DavisAre** [comment]
Hi, I've published the extension to open-vsx.org. https://open-vsx.org/extension/davis-are/drupal-sdc-helper

**Comment by DavisAre** [comment]
Hi, I've published the extension to open-vsx.org. https://open-vsx.org/extension/davis-are/drupal-sdc-helper
